### ISSUE TITLE
request for dataset

### ISSUE THREAD

**Issue by Yizhichaoai** [bok-bok/MSOC#1]
Dear author:
I am a master student of Xinjiang University, and my research direction is deepfake detection. I'd like to request to download Fakeavceleb dataset for developing multimodal deepfake detection algorithm.However, I applied several times on the official website of this dataset but still got no reply. As far as I know, many people have encountered this problem. 
Could you please send me the download link or script?

**Comment by yzyouzhang** [comment]
I am not sure if we can share the dataset. Did you follow the instructions at the [FakeAVCeleb download page](https://sites.google.com/view/fakeavcelebdash-lab/download)?

**Comment by Yizhichaoai** [comment]
> I am not sure if we can share the dataset. Did you follow the instructions at the [FakeAVCeleb download page](https://sites.google.com/view/fakeavcelebdash-lab/download)?
I have complied with the license agreement. Could you please send me a copy of the downloaded email content? I will share my tutor's homepage with you to confirm my identity. My email is 107552404073@stu.xju.edu.cn

**Comment by yzyouzhang** [comment]
I just emailed you about what I think we can help.
